spring:
  datasource:
      url: jdbc:mysql://xxxxxx:3306/test_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xxxxx
      password: xxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

